[Infra] Fix build error:no member named 'unique' in 'std::shared_ptr<lynx::PropBundleImpl::SharedData>
Use "use_count() != 1" instead of "!unique()" when checking whether PropBundleImpl shared data needs a copy.

issue:m-6888792555